// constants/chatConstant.js
export const CHAT_GET_MESSAGES_REQUEST = "CHAT_GET_MESSAGES_REQUEST";
export const CHAT_GET_MESSAGES_SUCCESS = "CHAT_GET_MESSAGES_SUCCESS";
export const CHAT_GET_MESSAGES_FAILURE = "CHAT_GET_MESSAGES_FAILURE";
export const CHAT_SEND_MESSAGE_REQUEST = "CHAT_SEND_MESSAGE_REQUEST";
export const CHAT_SEND_MESSAGE_SUCCESS = "CHAT_SEND_MESSAGE_SUCCESS";
export const CHAT_SEND_MESSAGE_FAILURE = "CHAT_SEND_MESSAGE_FAILURE";
